language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t akansha21/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true akansha21/docker-react npm run test
